# Homebrew formula for labelize
# Install: brew install GOODBOY008/labelize/labelize
# Or: brew tap GOODBOY008/labelize && brew install labelize
#
# Auto-generated by release workflow — do not edit manually.

class Labelize < Formula
  desc "Turn ZPL/EPL into pixels — label rendering, simplified."
  homepage "https://github.com/GOODBOY008/labelize"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GOODBOY008/labelize/releases/download/v1.0.0/labelize-aarch64-apple-darwin.tar.gz"
      sha256 "5920b026f461c751912e08e4dd03a4da2e686bef4f0baa73c3b93e1886ee9181"
    else
      url "https://github.com/GOODBOY008/labelize/releases/download/v1.0.0/labelize-x86_64-apple-darwin.tar.gz"
      sha256 "83c707011d01f53115d92723533720408be2179eab54bc50ba9d179eb0c0b42e"
    end
  end

  on_linux do
    url "https://github.com/GOODBOY008/labelize/releases/download/v1.0.0/labelize-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "15a59e9673908a3a9b3750fd90228b8dc702b5341212cd2cc504a03b58f7e6e5"
  end

  def install
    bin.install "labelize"
  end

  test do
    assert_match "labelize", shell_output("#{bin}/labelize --version")
  end
end
