# Homebrew formula for labelize
# Install: brew install GOODBOY008/labelize/labelize
# Or: brew tap GOODBOY008/labelize && brew install labelize
#
# Auto-generated by release workflow — do not edit manually.

class Labelize < Formula
  desc "Turn ZPL/EPL into pixels — label rendering, simplified."
  homepage "https://github.com/GOODBOY008/labelize"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/GOODBOY008/labelize/releases/download/v0.4.0/labelize-aarch64-apple-darwin.tar.gz"
      sha256 "9019c3272ac7df9f02c2531faac917c12f033e03bab386e0c123aa7b65be72bb"
    else
      url "https://github.com/GOODBOY008/labelize/releases/download/v0.4.0/labelize-x86_64-apple-darwin.tar.gz"
      sha256 "c180acaa3673a0ed13818b936291b6748bb07bbb4f332af76110df45f6bfd375"
    end
  end

  on_linux do
    url "https://github.com/GOODBOY008/labelize/releases/download/v0.4.0/labelize-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "810770087180c5dba3fe754c8653d6593be3721701583378131852b104f2b77e"
  end

  def install
    bin.install "labelize"
  end

  test do
    assert_match "labelize", shell_output("#{bin}/labelize --version")
  end
end
